config/routes.rb
require 'sidekiq/web'
require 'admin_constraint'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new
  get '/sidekiq' => 'signins#new'

  namespace :student do
    get :signup, to: 'signups#new'
    post :profiles, to: "signups#create"

    resource :location_details, only: :show

    resources :cookies, only: :create

    resource :dashboard, only: :show
    resource :profile, only: [:show, :edit, :update]

    resources :teams, except: :destroy
    resources :team_memberships, only: :destroy
    resources :team_locations, only: :edit

    resources :team_submissions
    resource :technical_checklist, only: [:edit, :update]
    resources :screenshots, only: [:index, :destroy]

    resource :team_photo_upload_confirmation, only: :show
    resource :profile_image_upload_confirmation, only: :show
    resource :team_submission_screenshot_upload_confirmation, only: :show
    resource :team_submission_file_upload_confirmation, only: :show

    resources :team_submission_pitch_presentations, only: [:new, :edit]

    resource :regional_pitch_event_selection,
      only: [:show, :create, :update, :destroy]

    resources :regional_pitch_events, only: :show
    resources :scores, only: [:show]

    resources :certificates, only: :create

    resources :image_process_jobs, only: :create
    resources :job_statuses, only: :show

    resources :mentors, only: :show
    resources :students, only: :show

    resources :team_member_invites, except: [:edit, :index]
    resources :mentor_invites, only: [:create, :destroy]
    resources :join_requests, only: [:new, :create, :update]

    resources :team_searches, except: [:index, :destroy]
    resources :mentor_searches, except: [:index, :destroy]

    resource :parental_consent_notice, only: [:new, :create]
  end

  namespace :mentor do
    get :signup, to: 'signups#new'
    post :profiles, to: "signups#create"

    resource :location_details, only: :show

    resource :dashboard, only: :show
    resource :profile, only: [:show, :edit, :update]
    resource :bio, only: [:edit, :update]

    resources :cookies, only: :create

    resources :team_searches, except: [:index, :destroy]
    resources :mentor_searches, except: [:index, :destroy]

    resources :teams, except: :destroy
    resources :team_memberships, only: :destroy
    resources :team_submissions
    resources :team_locations, only: :edit

    resources :certificates, only: :create

    resource :technical_checklist, only: [:edit, :update]
    resources :screenshots, only: [:index, :destroy]

    resource :team_photo_upload_confirmation, only: :show
    resource :profile_image_upload_confirmation, only: :show

    resource :team_submission_screenshot_upload_confirmation, only: :show
    resource :team_submission_file_upload_confirmation, only: :show

    resources :team_submission_pitch_presentations, only: [:new, :edit]

    resources :image_process_jobs, only: :create
    resources :job_statuses, only: :show

    resources :team_member_invites, except: [:edit, :index]
    resources :join_requests, except: [:index, :edit]
    resources :mentor_invites, only: [:show, :update, :destroy]

    resources :mentors, only: :show
    resources :students, only: :show

    resources :background_checks, only: [:new, :create, :show]

    resource :regional_pitch_event_selection,
      only: [:new, :show, :create, :update, :destroy]
    resources :regional_pitch_events, only: :show
    resources :scores, only: [:show]
  end

  namespace :regional_ambassador do
    get :signup, to: 'signups#new'
    post :profiles, to: "signups#create"

    resource :location_details, only: :show

    resource :dashboard, only: :show
    resource :profile, only: [:show, :edit, :update]
    resource :account, only: :update

    resources :accounts, only: [:index, :show, :edit, :update]

    resources :unmatched_students, only: :index
    resources :unmatched_mentors, only: :index
    resources :unmatched_teams, only: :index

    resources :teams, only: [:show, :index]
    resources :team_submissions, only: [:index, :show]
    resources :team_memberships, only: :destroy

    resources :exports, only: :create

    resource :profile_image_upload_confirmation, only: :show

    resources :background_checks, only: [:new, :create, :show]

    resources :regional_pitch_events
    resources :regional_pitch_event_participations, only: [:new, :create, :destroy]
    resources :judge_assignments, only: [:new, :create, :destroy]

    resources :scores, only: [:index, :show]

    resources :messages
    resources :multi_messages
    resources :message_deliveries, only: :create
  end

  namespace :judge do
    get :signup, to: 'signups#new'
    post :profiles, to: "signups#create"

    resource :location_details, only: :show

    resource :profile, only: [:show, :edit, :update]

    resource :profile_image_upload_confirmation, only: :show

    resource :dashboard, only: :show

    resource :mentor_profile

    resources :submission_scores, only: [:new, :edit, :update]

    resources :team_submissions, only: [] do
      resources :technical_checklist_verifications, only: [:new, :create]
    end

    resource :regional_pitch_event_selection, only: [:show, :create, :update, :destroy]
    resources :regional_pitch_events, only: :show
  end

  namespace :admin do
    resource :dashboard, only: :show

    resources :profiles
    resources :profile_locations, only: :edit
    resources :regional_ambassadors, only: [:index, :show, :update]

    resources :teams, except: :destroy
    resources :team_submissions, except: :destroy
    resources :team_memberships, only: [:destroy, :create]
    resources :team_locations, only: :edit
    resources :team_submission_certificates, only: :update

    resources :background_checks, only: :index
    resources :background_check_sweeps, only: :create

    resources :signup_attempts, only: :index
    resources :signup_invitations, only: :create

    resources :regional_pitch_events, only: [:index, :show, :update]
    resources :regional_pitch_event_participations, only: :destroy

    resources :scores, only: [:index, :show]
    resources :semifinals_scores, only: [:index, :show]
    resources :submission_score_restorations, only: :update


    resource :mentor_drop_out, only: :create
    resource :paper_parental_consent, only: :create

    resources :exports, only: :create

    resource :season_schedule_settings, only: [:edit, :update]
  end

  namespace :application do
    resource :dashboard, only: :show
  end

  resources :password_resets, only: [:new, :create]
  resources :passwords, only: [:new, :create]

  resources :parental_consents, only: [:new, :create, :show]
  resources :consent_waivers, only: [:new, :create, :show]

  resources :teams, only: :show
  resources :apps, controller: :team_submissions, only: :show
  resources :technical_checklists, only: :show

  resources :signup_attempts, only: [:create, :show, :update]
  resources :signup_attempt_confirmations, only: :new

  resources :email_confirmations, only: :new

  resource :locale_switch, only: :create

  resources :geolocation_results, only: :index

  get 'login', to: 'signins#new', as: :login
  get 'signin', to: 'signins#new', as: :signin

  get 'signup', to: 'signups#new', as: :signup

  match 'logout',  to: 'signins#destroy', as: :logout, via: [:get, :delete]
  match 'signout', to: 'signins#destroy', as: :signout, via: [:get, :delete]

  resources :signins, only: :create

  resource :token_error, only: :show
  resource :timeout_error, only: :show

  root to: "application/dashboards#show"
end

app/controllers/legacy/v2/judge/regional_pitch_event_selections_controller.rb
module Legacy
  module V2
    module Judge
      class RegionalPitchEventSelectionsController < JudgeController
        def show
          if params[:event_id]
            do_create(params)
          else
            do_destroy
          end
        end

        def create
          do_create(params)
        end

        def destroy
          do_destroy
        end

        private
        def do_destroy
          old_event = current_judge.selected_regional_pitch_event

          current_judge.remove_from_live_event

          SendPitchEventRSVPNotifications.perform_later(
            current_judge.id,
            judge_leaving_event_id: old_event.id
          )

          redirect_to [:judge, :dashboard],
            success: t("controllers.judge.regional_pitch_event_selections.destroy.success")
        end

        def do_create(params)
          old_event = current_judge.selected_regional_pitch_event

          current_judge.remove_from_live_event

          event = RegionalPitchEvent.find(params.fetch(:event_id))
          current_judge.regional_pitch_events << event
          current_judge.save!

          SendPitchEventRSVPNotifications.perform_later(
            current_judge.id,
            judge_leaving_event_id: old_event.id,
            judge_joining_event_id: event.id
          )

          redirect_to [:judge, current_judge.selected_regional_pitch_event],
            success: t("controllers.judge.regional_pitch_event_selections.create.success")
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/background_checks_controller.rb
module Legacy
  module V2
    module Mentor
      class BackgroundChecksController < MentorController
        include Concerns::BackgroundCheckController

        private
        def current_profile
          current_mentor
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/cookies_controller.rb
module Legacy
  module V2
    module Mentor
      class CookiesController < MentorController
        def create
          cookies.permanent[params.fetch(:name)] = params.fetch(:value)
          head 200
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/dashboards_controller.rb
module Legacy
  module V2
    module Mentor
      class DashboardsController < MentorController
        def show
          @teams = current_mentor.teams.current.order("teams.name")
        end

        private
        def create_judge_mentor_on_dashboard
          if current_account.judge_profile.present? and current_account.mentor_profile.nil?
            current_account.create_mentor_profile!({
              school_company_name: current_account.judge_profile.company_name,
              job_title: current_account.judge_profile.job_title,
            })

            flash.now[:success] = t("controllers.mentor.dashboards.show.mentor_profile_created")
          end
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/honor_code_agreements_controller.rb
module Legacy
  module V2
    module Mentor
      class HonorCodeAgreementsController < MentorController
        include Concerns::HonorCodeAgreementController
      end
    end
  end
end

app/controllers/legacy/v2/mentor/image_process_jobs_controller.rb
module Legacy
  module V2
    module Mentor
      class ImageProcessJobsController < MentorController
        def create
          job = ProcessScreenshotsJob.perform_later(current_team.submission, params.fetch(:keys))
          render json: { status_url: mentor_job_status_url(job.job_id) }
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/job_statuses_controller.rb
module Legacy
  module V2
    module Mentor
      class JobStatusesController < MentorController
        def show
          job = Job.find_by(job_id: params.fetch(:id))
          render json: { status: job.status }
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/join_requests_controller.rb
module Legacy
  module V2
    class Mentor::JoinRequestsController < MentorController
      def new
        @team = Team.find(params.fetch(:team_id))
      end

      def create
        @team = Team.find(params.fetch(:team_id))
        join_request = JoinRequest.new(requestor: current_mentor,
                                      joinable: @team)
        if join_request.save
          redirect_to [:mentor, join_request],
                      success: t("controllers.mentor.join_requests.create.success",
                                name: @team.name)
        else
          render :new
        end
      end

      def show
        @join_request = current_mentor.join_requests.find(params.fetch(:id))
      end

      def update
        join_request = JoinRequest.find(params.fetch(:id))
        join_request.public_send("#{params.fetch(:status)}!")

        redirect_back fallback_location: mentor_dashboard_path,
          success: t("controllers.mentor.join_requests.update.success",
                    name: join_request.requestor_first_name,
                    status: params.fetch(:status))
      end
    end
  end
end

app/controllers/legacy/v2/mentor/location_details_controller.rb
module Legacy
  module V2
    module Mentor
      class LocationDetailsController < MentorController
        helper_method :current_profile

        def show
          render template: "location_details/show"
        end

        private
        def current_profile
          current_mentor
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/mentor_invites_controller.rb
module Legacy
  module V2
    module Mentor
      class MentorInvitesController < MentorController
        def show
          @invite = current_mentor.mentor_invites.find_by(invite_token: params.fetch(:id)) ||
            NullInvite.new
        end

        def update
          if invite = current_mentor.mentor_invites.pending.find_by(invite_token: params.fetch(:id))
            invite.update_attributes(invite_params)
            redirect_based_on_status(invite)
          else
            redirect_to mentor_dashboard_path, alert: t("controllers.invites.update.failure")
          end
        end

        def destroy
          @invite = MentorInvite.find_by(team_id: current_mentor.team_ids,
                                        invite_token: params.fetch(:id))
          @invite.destroy
          redirect_back fallback_location: mentor_dashboard_path,
            success: t("controllers.invites.destroy.success", name: @invite.invitee_name)
        end

        private
        def redirect_based_on_status(invite)
          if invite.accepted?
            @path = mentor_team_path(invite.team)
            @msg = t("controllers.team_member_invites.update.success")
          else
            @path = mentor_dashboard_path
            @msg = t("controllers.team_member_invites.update.not_accepted")
          end

          redirect_to @path, success: @msg
        end

        def invite_params
          params.require(:team_member_invite).permit(:status)
        end

        class NullInvite
          def status
            "missing"
          end
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/mentor_searches_controller.rb
module Legacy
  module V2
    module Mentor
      class MentorSearchesController < MentorController
        include Concerns::MentorSearchesController

        private
        def user
          current_mentor
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/mentors_controller.rb
module Legacy
  module V2
    class Mentor::MentorsController < MentorController
      def show
        @mentor = MentorProfile.find(params.fetch(:id))
        @mentor_invite = MentorInvite.new
      end
    end
  end
end

app/controllers/legacy/v2/mentor/profile_image_upload_confirmations_controller.rb
module Legacy
  module V2
    module Mentor
      class ProfileImageUploadConfirmationsController < MentorController
        include Concerns::ProfileImageUploadConfirmationController
      end
    end
  end
end

app/controllers/legacy/v2/mentor/profiles_controller.rb
module Legacy
  module V2
    module Mentor
      class ProfilesController < MentorController
        include Concerns::ProfileController

        before_action :expertises

        def profile_params
          [
            :school_company_name,
            :job_title,
            :bio,
            :accepting_team_invites,
            :virtual,
            :connect_with_mentors,
            { expertise_ids: [] },
          ]
        end

        private
        def account
          current_mentor
        end

        def expertises
          @expertises ||= Expertise.all
        end

        def edit_profile_path
          edit_mentor_profile_path
        end

        def account_param_root
          :mentor_profile
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/regional_pitch_event_selections_controller.rb
module Legacy
  module V2
    module Mentor
      class RegionalPitchEventSelectionsController < MentorController
        def new
          @teams = current_mentor.teams.current.includes(:regional_pitch_events)
        end

        def create
          params.fetch(:regional_pitch_events_teams).each do |team_id, event_id|
            team = current_mentor.teams.current.find(team_id)
            event = team.eligible_events.detect { |e| e.id.to_s == event_id }
            old_event = team.selected_regional_pitch_event

            if event
              team.remove_from_live_event
            else
              head 404 and return
            end

            if event.live?
              team.regional_pitch_events << event
              team.save!
            end

            SendPitchEventRSVPNotifications.perform_later(
              team.id,
              leaving_event_id: old_event.id,
              joining_event_id: event.id
            )

            head 200
          end
        end
      end
    end
  end
end

app/controllers/legacy/v2/mentor/students_controller.rb
module Legacy
  module V2
    module Mentor
      class StudentsController < MentorController
        def show
          @student = StudentProfile.find(params.fetch(:id))
        end
      end
    end
  end
end

app/views/mentor/regional_pitch_event_selections/new.en.html.erb
<h1 class="appy-title">
  Review
  <% if SeasonToggles.select_regional_pitch_event? %>&amp; Select<% end %>
  Regional Pitch Events
</h1>

<% if SeasonToggles.select_regional_pitch_event? and @teams.flat_map(&:eligible_events).any? %>
  <div class="mentor-regional-pitch-events__save-selections standalone-buttons">
    <div class="actions">
      <button class="save-mentor-pitch-events appy-button"
              data-url="<%= mentor_regional_pitch_event_selection_path %>">
        Save changes
      </button>

      or

      <%= link_to 'cancel', mentor_teams_path %>
    </div>
  </div>
<% end %>

<div class="flex-row mentor-regional-pitch-events__team-review">
  <% @teams.each do |team| %>
    <div class="flex-col-md-6">
      <div data-team-id="<%= team.id %>"
          class="card team-card standalone-buttons">
        <div class="card__heading">
          <%= team.name %>
        </div>

        <div class="card__body">
          <div class="card-body__img">
            <%= image_tag team.team_photo, width: 150, height: 100 %>
          </div>

          <div class="card-body__details">
            <strong><%= team.name %></strong><br />
            <strong>Division:</strong> <%= team.division_name.titleize %><br />

            <small>
              <%= team.primary_location %><br />

              <% if team.submission.present? %>
                <%= link_to 'See how it looks to the judges',
                  app_url(team.submission),
                  target: :_blank %>
              <% else %>
                <strong class="has-danger">
                  <%= team.name %> has not begun their app submission!
                </strong>
              <% end %>
            </small>
          </div>

          <% if team.submission.present? %>
            <div style="clear: both;">
              <strong>Select a Regional Pitch Event:</strong>

              <ul class="card-body__selection">
                <% team.eligible_events.each do |event| %>
                  <li>
                    <label class="<%= 'selected' if team.selected_regional_pitch_event.id == event.id %>">
                      <%= radio_button_tag "team_#{team.id}_events",
                        event.id,
                        team.selected_regional_pitch_event.id == event.id,
                        disabled: !SeasonToggles.select_regional_pitch_event?,
                        id: "team_#{team.id}_event_#{event.id}" %>

                      <%= event.name %>
                      <%= link_to '(more info)',
                        mentor_regional_pitch_event_path(event),
                        data: {
                          modal_trigger: "team_#{team.id}_event_info_#{event.id}",
                        } %>
                    </label>
                  </li>

                  <div class="modalify"
                      data-heading="<%= event.name %> Details"
                      id="team_<%= team.id %>_event_info_<%= event.id %>">
                    <% if event.live? %>
                      <p><strong>Division:</strong> <%= event.division_names %></p>
                      <p><strong>City:</strong> <%= event.city %></p>
                      <p><strong>Date / time:</strong> <%= event.date_time %></p>
                      <p><strong>Address:</strong> <%= event.venue_address %></p>

                      <% if event.eventbrite_link %>
                        <p>
                          <%= link_to event.eventbrite_link,
                            event.eventbrite_link,
                            target: :_blank %>
                        </p>
                      <% end %>
                    <% else %>
                      <p>
                        By default, all teams with completed submissions are entered
                        into virtual judging.
                      </p>

                      <p>
                        Virtual judging is a competition between all teams in the same
                        region and division.
                      </p>

                      <p>
                        If you select this event — or you simply do not select any
                        live events — your team's completed submission will be judged online.
                      </p>
                    <% end %>

                    <% if SeasonToggles.select_regional_pitch_event? %>
                      <div class="modal-actions">
                        <button class="appy-button modalify__close"
                                data-selects="team_<%= team.id %>_event_<%= event.id %>">
                          Select
                        </button>
                        or
                        <%= link_to 'cancel', '#', class: "modalify__close" %>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if SeasonToggles.select_regional_pitch_event? and @teams.flat_map(&:eligible_events).any? %>
  <div class="mentor-regional-pitch-events__save-selections standalone-buttons">
    <div class="actions">
      <button class="save-mentor-pitch-events appy-button"
              data-url="<%= mentor_regional_pitch_event_selection_path %>">
        Save changes
      </button>

      or

      <%= link_to 'cancel', mentor_teams_path %>
    </div>
  </div>
<% end %>